// File: src/utils/reportHelpers.js

import { TRANSACTION_TYPES } from './constants';
import { getCategoryById } from './categories';
import { formatAmount } from './currencies';

/**
 * Get start/end of the week containing `date` (Monday–Sunday).
 */
export const getWeekRange = (date = new Date()) => {
    const d = new Date(date);
    const day = d.getDay();
    const diffToMonday = day === 0 ? -6 : 1 - day;
    const start = new Date(d);
    start.setDate(d.getDate() + diffToMonday);
    start.setHours(0, 0, 0, 0);
    const end = new Date(start);
    end.setDate(start.getDate() + 6);
    end.setHours(23, 59, 59, 999);
    return { start, end };
};

/**
 * Generate aggregated report data from a set of transactions.
 */
export const generateReportData = (transactions) => {
    if (!transactions || transactions.length === 0) {
        return {
            totalIncome: 0,
            totalExpense: 0,
            balance: 0,
            transactionCount: 0,
            dailyAverage: 0,
            categoryBreakdown: [],
            topCategories: [],
            dayCount: 0,
        };
    }

    const incomeTotal = transactions
        .filter((t) => t.type === TRANSACTION_TYPES.INCOME)
        .reduce((sum, t) => sum + t.amount, 0);

    const expenseTotal = transactions
        .filter((t) => t.type === TRANSACTION_TYPES.EXPENSE)
        .reduce((sum, t) => sum + t.amount, 0);

    // Calculate unique days spanned
    const dates = transactions.map((t) => new Date(t.date).toDateString());
    const uniqueDays = new Set(dates).size;
    const dayCount = Math.max(uniqueDays, 1);

    // Category breakdown (expenses only)
    const catMap = {};
    transactions
        .filter((t) => t.type === TRANSACTION_TYPES.EXPENSE)
        .forEach((t) => {
            if (!catMap[t.category]) {
                catMap[t.category] = 0;
            }
            catMap[t.category] += t.amount;
        });

    const categoryBreakdown = Object.entries(catMap)
        .map(([catId, amount]) => {
            const cat = getCategoryById(catId);
            return {
                id: catId,
                label: cat?.label || 'Unknown',
                icon: cat?.icon || 'help-circle-outline',
                color: cat?.color || '#888',
                amount,
                percentage: expenseTotal > 0 ? Math.round((amount / expenseTotal) * 100) : 0,
            };
        })
        .sort((a, b) => b.amount - a.amount);

    const topCategories = categoryBreakdown.slice(0, 5);

    return {
        totalIncome: incomeTotal,
        totalExpense: expenseTotal,
        balance: incomeTotal - expenseTotal,
        transactionCount: transactions.length,
        dailyAverage: expenseTotal / dayCount,
        categoryBreakdown,
        topCategories,
        dayCount,
    };
};

/**
 * Format report data into a shareable text summary.
 */
export const formatReportText = (reportData, currencySymbol, periodLabel, currencyCode = 'INR') => {
    const lines = [
        `📊 ExpenseFlow Report — ${periodLabel}`,
        '',
        `💰 Income: ${currencySymbol}${formatAmount(reportData.totalIncome, currencyCode)}`,
        `💸 Expense: ${currencySymbol}${formatAmount(reportData.totalExpense, currencyCode)}`,
        `📈 Balance: ${currencySymbol}${formatAmount(reportData.balance, currencyCode)}`,
        '',
        `📅 ${reportData.transactionCount} transactions over ${reportData.dayCount} days`,
        `📊 Daily Average Spend: ${currencySymbol}${formatAmount(reportData.dailyAverage, currencyCode)}`,
    ];

    if (reportData.topCategories.length > 0) {
        lines.push('', '🏆 Top Categories:');
        reportData.topCategories.forEach((cat, i) => {
            lines.push(`  ${i + 1}. ${cat.label}: ${currencySymbol}${formatAmount(cat.amount, currencyCode)} (${cat.percentage}%)`);
        });
    }

    lines.push('', '— Generated by ExpenseFlow');
    return lines.join('\n');
};
