import '../services/demographics_service.dart';

class DemographicRoasts {
  static const Map<DemographicCategory, List<String>> roasts = {
    // 100 Child Roasts
    DemographicCategory.child: [
      "Bro you're literally a child. Put the phone down and go touch grass at the playground.",
      "You're not old enough to have cortisol stress. Your biggest problem is bedtime.",
      "A whole child is using this app. Where are your parents? Do they know about this?",
      "You look way too young to be this stressed. Go watch Cocomelon or something.",
      "Little bro hasn't even hit puberty and is already scanning for cortisol. We're doomed.",
      "Your cortisol reading is invalid because you still believe in the tooth fairy.",
      "This app is rated M for Mature. You are neither of those things.",
      "You're like 7. Your only stress should be which crayon to use next.",
      "Baby face detected. The AI refuses to roast a minor... just kidding. Go do your homework.",
      "You look young enough to still have a bedtime. Respect it.",
      "Did you steal your iPad to use this app or did your parents just give up?",
      "You look like you'd cry if someone ate the last chicken nugget.",
      "Stress? Bro, your hardest decision today was Apple juice or Orange juice.",
      "You're too young to be worried about cortisol. Worry about your multiplication tables.",
      "If you're stressed now, just wait until middle school ruins your life.",
      "Go back to playing Roblox. The adult world is full of taxes and back pain.",
      "You still have all your baby teeth and you're checking your stress levels?",
      "Bro looks like he throws a tantrum when the iPad dies.",
      "Your high cortisol is probably just a sugar rush from eating too many gummy worms.",
      "The only thing you should be scanning for is monsters under your bed.",
      "You look like you unironically watch Minecraft YouTubers for 6 hours a day.",
      "Are you stressed because your mom said we have food at home?",
      "You're literally knee-high to a grasshopper. Stop pretending to have adult problems.",
      "Did the recess bell ring late today? Is that why you're tweaking?",
      "Bruh, you are the reason restaurants have coloring menus.",
      "You look like you have to ask permission to use the internet.",
      "Your stress is 100% caused by not getting the toy in your Happy Meal.",
      "You're basically a glorified toddler. Go take a nap.",
      "You look like you still use training wheels on your bike.",
      "Are you stressed because someone stepped on your Lego structure?",
      "Bro's biggest fear is the dark and he's acting like he pays a mortgage.",
      "You still watch cartoons in your pajamas on Saturday mornings. Shut up.",
      "Your high cortisol is just you realizing you have a spelling test tomorrow.",
      "You look like you think 16 is 'really old'. Wait till your knees start popping.",
      "The only drama in your life is trying to get the good swing at the park.",
      "You look like you eat the crust off your sandwiches. Grow up.",
      "Are you mad because your juice box straw poked through the other side?",
      "Bro, you still need help reaching the sink. Relax.",
      "Your stress is fake. Sort of like your belief in Santa Claus.",
      "You look like you cry when you step on a crack in the sidewalk.",
      "You're stressed? You literally get summers off. Be quiet.",
      "Did your older sibling take the player one controller again?",
      "You look like your mom still picks out your clothes for the week.",
      "Bro's cortisol spiked because he lost his favorite Hot Wheels car.",
      "You have the emotional maturity of a goldfish. Go swim in circles.",
      "You look like you still need the bumpers at the bowling alley.",
      "Your biggest achievement this year was staying up past 9 PM.",
      "Are you stressed because you can't figure out long division?",
      "You look like you still laugh at fart jokes. Actually, never mind, adults do that too.",
      "Bro, your shoe is untied. Focus on that before your cortisol.",
      "You look like you think chocolate milk comes from brown cows.",
      "Your stress is just you realizing you have to share your toys today.",
      "You still use safety scissors. You don't know real danger or stress.",
      "Are you tweaking because your iPad screen time ran out?",
      "Bro looks like he still believes the moon follows his car.",
      "Your cortisol is high because you ate a watermelon seed and think a tree will grow in your stomach.",
      "You look like you still think quicksand is a major life threat.",
      "You're stressed because you stepped on a crunchy leaf and it wasn't crunchy.",
      "Did you get the wrong color Gatorade at soccer practice?",
      "You look like you still have to wear arm floaties in the pool.",
      "Your high cortisol is from trying to assemble a 20-piece puzzle.",
      "Bro, you still think cooties are a real medical condition.",
      "You look like you get scared when the toast pops out of the toaster.",
      "Are you stressed because your mom left you alone in the grocery checkout line?",
      "You still think swallowing gum stays in your stomach for 7 years.",
      "You look like you thought the dog ate your homework but you don't even have a dog.",
      "Your stress is from trying to beat the kitchen light when you turn it off at night.",
      "Bro's biggest life decision is which stuffed animal gets to sleep on the bed.",
      "You look like you still try to balance the light switch perfectly in the middle.",
      "Are you stressed because you saw your teacher at the grocery store?",
      "You still think the crust makes your hair curly. Spoiler: it doesn't.",
      "You look like you still get excited when you see a school bus.",
      "Your cortisol spiked because you walked into a spider web.",
      "Bro, your biggest heartbreak was dropping your ice cream cone.",
      "You look like you try to drink the rain when it falls.",
      "Are you tweaking because you thought a shadow in your room was a ghost?",
      "You still think the floor is lava. Actually, that never gets old.",
      "You look like you still try to stay up to catch the tooth fairy.",
      "Your stress is from trying to blow a bubble with bubblegum and failing.",
      "Bro's biggest flex is knowing how to tie his shoes.",
      "You look like you still think clouds are made of cotton candy.",
      "Are you stressed because you can't snap your fingers yet?",
      "You still try to step inside the squares on the sidewalk without touching the lines.",
      "You look like you still get scared of the vacuum cleaner.",
      "Your cortisol is high because you thought thunder was clouds bowling.",
      "Bro, you still think chocolate milk comes from brown cows.",
      "You look like you still try to dig a hole to China in the sandbox.",
      "Are you stressed because you thought the TV characters could see you?",
      "You still try to hold your breath when driving through a tunnel.",
      "You look like you still think eating crust gives you curly hair.",
      "Your stress is from trying to push all the colors down on a multi-color pen at once.",
      "Bro's biggest mystery is where the lost sock goes.",
      "You look like you still try to sneak a cookie before dinner.",
      "Are you tweaking because you thought a watermelon seed would grow in your stomach?",
      "You still try to jump off the swing at the highest point to look cool.",
      "You look like you still get excited when the DVD logo hits the corner of the screen.",
      "Your cortisol spiked because you tried to lick your elbow and failed.",
      "Bro, you still think the moon follows your car.",
      "You look like you still try to catch snowflakes on your tongue.",
      "Are you stressed because you thought you swallowed a bug while biking?",
    ],

    // 100 Teen Male Roasts
    DemographicCategory.teenMale: [
      "Teen boy detected. Your cortisol is 90% Fortnite rage and 10% unrequited crush.",
      "You look like you think having a middle part and a vape makes you interesting. It doesn't.",
      "Gen Alpha male detected. You definitely say 'skibidi' unironically.",
      "Bro is a teenager cosplaying as an adult. The voice crack gave you away.",
      "You radiate 'my mom still makes my lunch' energy and there's nothing wrong with that honestly.",
      "Young king, your cortisol is high because you spent 12 hours gaming and forgot to eat.",
      "You look like you just discovered what cologne is and now you bathe in it.",
      "Teen male. Your biggest personality trait is your Discord server that has 4 members.",
      "You have the confidence of someone who has never paid a bill in their life.",
      "Bro your brain isn't even fully developed yet and you're already this stressed? GG.",
      "You look like you unironically call yourself an 'alpha male' in Xbox lobbies.",
      "Your stress comes from your mom telling you to clean your room while you're in a ranked match.",
      "Bro definitely thinks listening to unreleased Playboi Carti makes him mysterious.",
      "You look like you practice your 'smolder' in the mirror for 30 minutes a day.",
      "Your cortisol is high because you still haven't figured out how to talk to women.",
      "You have exactly 3 hoodies and you rotate them like they're designer fashion.",
      "Bro's entire internet history is just 'how to get a jawline fast' and Minecraft mods.",
      "You definitely flex your mom's car on Snapchat like you bought it.",
      "You look like you get aggressively competitive during P.E. dodgeball.",
      "Your high cortisol is just the sheer terror of having to present a project in front of your crush.",
      "Bro thinks putting 'entrepreneur' in his bio after selling one pair of Jordans is valid.",
      "You look like you base your entire personality on whatever anime protagonist you watched last.",
      "Are you stressed because you just realized your patchy mustache isn't actually a beard?",
      "You definitely use 3-in-1 shampoo/conditioner/body wash and wonder why your hair feels like hay.",
      "Your cortisol spiked because you sent a risky text and she left you on delivered for 5 hours.",
      "Bro, hiding your emotions behind irony isn't a personality type.",
      "You look like you still ask 'where's my hug at?'",
      "Your biggest life achievement so far is a high score in a game that nobody plays anymore.",
      "You definitely have led LED strip lights in your room set permanently to red.",
      "Bro's stress is 100% caused by his group chat leaking his terrible DMs.",
      "You look like you think wearing shorts in 30-degree weather makes you tough.",
      "Your cortisol is high because you just found out you actually have to study for the SATs.",
      "You definitely pretend to like black coffee but put 6 packets of sugar in it when no one's looking.",
      "Bro thinks having a messy room is 'aesthetic'—no, it's a biohazard.",
      "You look like you still haven't figured out deodorant isn't a substitute for a shower.",
      "Your stress comes from trying to maintain a 1000-day Snapchat streak with someone you don't even talk to.",
      "You definitely ask your barber for 'a little off the top' and then complain when it looks the same.",
      "Bro thinks knowing the lyrics to one underground rap song makes him a music connoisseur.",
      "You look like you flex your height as your only redeeming quality.",
      "Your cortisol is high because you just realized you have to write an essay that's due tomorrow.",
      "You definitely try to lower your voice an octave when you answer the phone around your friends.",
      "Bro thinks 'I'm just brutally honest' is an excuse for having zero social awareness.",
      "You look like you own exactly one suit and it doesn't fit you anymore.",
      "Your stress comes from your favorite streamer getting canceled.",
      "You definitely spend 40 minutes on your hair just to make it look 'messy'.",
      "Bro thinks knowing how to do a kickflip is a viable career path.",
      "You look like you still use Axe Body Spray. Like, a lot of it.",
      "Your cortisol spiked because you just checked your screen time and it's 11 hours.",
      "You definitely put 'future billionaire' in your Instagram bio.",
      "Bro's biggest stressor is deciding which meme to post on his spam account.",
      "You look like you think lifting weights will fix your terrible personality. It won't.",
      "Your stress is 100% fueled by the group chat getting too quiet when you send a joke.",
      "You definitely pretend you 'don't care about relationships' because you can't get one.",
      "Bro thinks watching 'Sigma male grindset' videos is self-improvement.",
      "You look like you still haven't learned how to do your own laundry.",
      "Your cortisol is high because your phone battery is at 2% and you don't have a charger.",
      "You definitely try to act unfazed when you trip in public, but your soul leaves your body.",
      "Bro thinks having a gaming PC makes him better than console players. Spoiler: you still bottom frag.",
      "You look like you base your political opinions entirely on meme pages.",
      "Your stress comes from your parents asking what you want to do after high school.",
      "You definitely wear a beanie indoors to cover up a bad haircut.",
      "Bro thinks avoiding eye contact makes him look cool and mysterious. You just look terrified.",
      "You look like you still think 'your mom' jokes are top-tier comedy.",
      "Your cortisol spiked because you accidentally liked a girl's picture from 2018.",
      "You definitely try to subtly flex your forearms when you talk.",
      "Bro's biggest life obstacle is waking up before noon on a weekend.",
      "You look like you only drink Monster Energy and wonder why your heart palpitations are so bad.",
      "Your stress is from trying to hide your search history from your mom.",
      "You definitely pretend to understand crypto so you sound smart in discord.",
      "Bro thinks wearing sweatpants to school every day is a valid fashion choice.",
      "You look like you still haven't mastered the firm handshake.",
      "Your cortisol is high because you just realized your crush likes your best friend.",
      "You definitely try to look brooding in group photos but just look constipated.",
      "Bro thinks watching an entire Netflix series in one day is a personality trait.",
      "You look like you write 'it is what it is' after every minor inconvenience.",
      "Your stress comes from your WiFi dropping mid-match.",
      "You definitely claim you 'don't study' but stay up till 3 AM cramming.",
      "Bro thinks having a dry sense of humor makes up for being boring.",
      "You look like your bedroom floor is 90% dirty clothes and 10% empty water bottles.",
      "Your cortisol spiked because a girl asked for a pencil and you didn't have one.",
      "You definitely try to speedrun homework the period before it's due.",
      "Bro's biggest fear is opening a Snapchat and not knowing how to reply.",
      "You look like you still use the front camera flash as a flashlight.",
      "Your stress is from trying to keep up with slang that changes every three hours.",
      "You definitely act like you don't care about your grades while silently panicking about your GPA.",
      "Bro thinks having a low Snapchat score makes him look mysterious.",
      "You look like you pretend not to know popular songs but secretly know all the lyrics.",
      "Your cortisol is high because you just realized you've been wearing your shirt inside out all day.",
      "You definitely try to act tough but sleep with a stuffed animal. It's okay, bro.",
      "Bro thinks ignoring texts makes him look busy. You're just annoying.",
      "You look like you still haven't figured out how to tie a tie.",
      "Your stress comes from trying to look cool while eating a messy burger.",
      "You definitely claim you're going to start going to the gym 'next week' every week.",
      "Bro thinks having a cracked screen protector adds character to his phone.",
      "You look like you still panic when the teacher asks you to read out loud.",
      "Your cortisol spiked because you waved at someone who was waving at the person behind you.",
      "You definitely try to act like you're not out of breath after walking up one flight of stairs.",
      "Bro's biggest regret is a haircut he got three years ago.",
      "You look like you still haven't learned the difference between 'your' and 'you're'.",
      "Your stress is from trying to maintain a cool posture while sitting in an uncomfortable chair.",
    ],

    // 100 Teen Female Roasts
    DemographicCategory.teenFemale: [
      "Teen girl detected. Your cortisol is 100% fueled by school drama and situationships.",
      "You look like your entire personality is based on your Spotify Wrapped.",
      "Young queen, the algorithm detected that your stress comes entirely from comparing yourself to influencers.",
      "You have 'I'm not like other girls but actually exactly like other girls' energy.",
      "Your cortisol spike is from posting a selfie and only getting 12 likes.",
      "You radiate 'my journal entries could be a Netflix series' energy.",
      "Teen girl. Your biggest stressor is whether he left you on read or just hasn't opened the app yet.",
      "You look like you have a Pinterest board called 'future apartment' but can't afford ramen.",
      "Your entire stress could be cured by deleting TikTok. But you won't. You never will.",
      "Young lady, put the phone down and study. Your parents didn't immigrate for this.",
      "You definitely diagnose yourself with a new mental illness every time you see a relatable TikTok.",
      "Your stress comes from having an extensive 12-step skincare routine that's destroying your skin barrier.",
      "Girl, your cortisol is high because you're romantically obsessed with a fictional character.",
      "You look like you apologize to inanimate objects when you bump into them.",
      "Your biggest fear is wearing the wrong aesthetic on the wrong day.",
      "You definitely have a private story just for complaining about minor inconveniences.",
      "Girl, your stress is 100% caused by overanalyzing a text that just said 'ok'.",
      "You look like you drink iced coffee every morning but complain about having anxiety. It's the caffeine, babes.",
      "Your cortisol spiked because you accidentally screenshotted a Snapchat chat.",
      "You definitely start a new hobby every week and abandon it after buying all the supplies.",
      "Girl, you have 400 photos of the sky in your camera roll that you'll never look at again.",
      "You look like you're holding together your entire friend group's emotional stability with a bobby pin.",
      "Your stress comes from trying to perfectly curate your Instagram grid.",
      "You definitely say 'I'm healing' just to justify taking a 5-hour daytime nap.",
      "Girl, your cortisol is high because you have to make a phone call to schedule an appointment.",
      "You look like you plan your outfits in your head before you fall asleep but end up wearing sweatpants.",
      "Your biggest achievement today was managing to do your winged eyeliner evenly.",
      "You definitely romanticize studying but spend 90% of the time making the notes look pretty.",
      "Girl, your stress is from realizing the 'messy bun' you threw up actually took 15 tries to look right.",
      "You look like you keep buying books you know you're never going to read.",
      "Your cortisol spiked because your favorite character died in a show you're watching.",
      "You definitely pretend your music taste is underground but your top artist is Taylor Swift.",
      "Girl, you have a notes app filled with unsent paragraphs to boys who don't deserve you.",
      "You look like you rewatch the same three comfort shows because new plots give you anxiety.",
      "Your stress comes from knowing you have to wash your hair tonight.",
      "You definitely claim you 'hate drama' but have a front-row seat with popcorn whenever it happens.",
      "Girl, your cortisol is high because you realized your camera roll is 90% selfies from the exact same angle.",
      "You look like you think astrology excuses your terrible communication skills.",
      "Your biggest fear is accidentally liking someone's post from 3 years ago while stalking them.",
      "You definitely hype up your friends in their comments but secretly feel insecure when you look in the mirror.",
      "Girl, your stress is 100% fueled by reading too much enemies-to-lovers trope fiction.",
      "You look like you still haven't figured out what your signature scent is.",
      "Your cortisol spiked because you saw a girl wearing the top you wanted but couldn't afford.",
      "You definitely try to act aloof but double text when they don't reply in 5 minutes.",
      "Girl, you have 'I need a matcha latte immediately or I will cry' energy.",
      "You look like you curate a hyper-specific playlist for every minor mood swing.",
      "Your stress comes from trying to look effortless when we all know it took 2 hours.",
      "You definitely own an embarrassing amount of lip glosses that are basically the exact same shade.",
      "Girl, your cortisol is high because you overpacked for a 2-day trip by bringing 7 outfits.",
      "You look like you give amazing advice to your friends but make the absolute worst decisions for yourself.",
      "Your biggest stressor is holding in a sneeze so you don't ruin your mascara.",
      "You definitely buy cute workout sets assuming it will magically motivate you to hit the gym.",
      "Girl, your stress is from mentally spending the money you don't have yet.",
      "You look like you have an entire photo album dedicated to screenshots of text messages as receipt evidence.",
      "Your cortisol spiked because a highly specific TikTok called out exactly what you were doing at that moment.",
      "You definitely pretend you like 'nature' but complain when there's a bug within a 5-mile radius.",
      "Girl, you have 'I'll just add it to my cart and look at it' energy.",
      "You look like you still panic when you have to calculate a tip.",
      "Your stress comes from trying to decipher if he's flirting or just being nice.",
      "You definitely use crystals to 'cleanse your energy' instead of just going to therapy.",
      "Girl, your cortisol is high because you have to present in front of the class and your voice might shake.",
      "You look like you get emotionally attached to seasonal drinks at Starbucks.",
      "Your biggest fear is running out of dry shampoo.",
      "You definitely say 'I have nothing to wear' while staring at a closet that's overflowing.",
      "Girl, your stress is 100% caused by procrastinating an assignment until 11:58 PM.",
      "You look like you still think your 'ugly phase' from middle school is visible to everyone.",
      "Your cortisol spiked because you accidentally sent a snap to the person you were talking about.",
      "You definitely act like you're an introvert but literally talk over everyone in the group.",
      "Girl, you have 'I need to go on a hot girl walk to process my emotions' energy.",
      "You look like you buy aesthetic organizers for your room but leave them empty on your desk.",
      "Your stress comes from trying to maintain perfect posture but slouching like a shrimp the second you look at your phone.",
      "You definitely pretend you don't care about Valentine's Day but secretly plot your whole outfit just in case.",
      "Girl, your cortisol is high because you just discovered a new split end.",
      "You look like you use sarcasm as a defense mechanism because genuine vulnerability terrifies you.",
      "Your biggest stressor is deciding which filter makes you look the most 'natural'.",
      "You definitely plan your entire future with a guy you just saw on the bus who didn't even notice you.",
      "Girl, your stress is from trying to keep a plant alive and watching it slowly die despite your efforts.",
      "You look like you still haven't accepted that middle parts just don't work for your face shape.",
      "Your cortisol spiked because you typed 'omg lol' with a completely straight, deadpan face.",
      "You definitely buy journals to 'get your life together' and only write on the first page.",
      "Girl, you have 'I'm currently in my villain era' energy but you're too nice to actually do anything.",
      "You look like you genuinely believe listening to sad music while sad will make you happier.",
      "Your stress comes from trying to get the perfect sunset picture before it completely fades.",
      "You definitely pretend you hate gossiping but actively say 'tell me everything' the second someone drops a hint.",
      "Girl, your cortisol is high because your phone is always at 4% and you refuse to plug it in.",
      "You look like you still harbor resentment towards a girl who wronged you in 7th grade.",
      "Your biggest fear is being perceived in public when you're just trying to buy snacks.",
      "You definitely say 'I'm so done' about 15 times a day but never actually finish anything.",
      "Girl, your stress is 100% fueled by comparing your behind-the-scenes to everyone else's highlight reel.",
      "You look like you still panic when someone asks what your hobbies are because you don't have any except scrolling.",
      "Your cortisol spiked because you just realized you've been pronouncing a common word wrong your whole life.",
      "You definitely act like you're fiercely independent but literally can't decide where to eat without help.",
      "Girl, you have 'I need a little treat to reward myself for doing the bare minimum' energy.",
      "You look like you organize your apps by color aesthetic but can never find the one you need.",
      "Your stress comes from realizing you have to start acting like a mature adult soon.",
      "You definitely pretend you aren't cold in your cute outfit even though your lips are turning blue.",
      "Girl, your cortisol is high because you just saw someone from high school when you were looking like a gremlin.",
      "You look like you still haven't mastered how to wink without looking like you're having a stroke.",
      "Your biggest stressor is trying to find the perfect emoji to convey 'I'm annoyed but trying to be chill'.",
      "You definitely say you're going to 'fix your sleep schedule' tonight and inevitably stay up till 2 AM anyway.",
    ],

    // 100 Adult Male Roasts
    DemographicCategory.adultMale: [
      "Adult male detected. You look like you think watching Joe Rogan counts as a personality.",
      "Grown man getting his cortisol checked by a meme app. Your father would be disappointed.",
      "You have the vibe of a guy who calls himself an 'entrepreneur' but sells dropshipped phone cases.",
      "Adult male. Your hairline is receding faster than your will to live.",
      "You look like you peaked in high school and have been running on fumes ever since.",
      "Bro is a grown man who still can't cook anything that isn't frozen or microwaved.",
      "You radiate 'I gym 6 days a week but still can't get a text back' energy.",
      "Adult male detected. The bags under your eyes have their own apartment lease.",
      "You look like you unironically use LinkedIn as a dating app.",
      "Grown man stress. You're one bad day away from buying a motorcycle and calling it therapy.",
      "Man, your cortisol is high because you just checked your credit score. Don't worry, we won't tell.",
      "You look like you explain movies to women who have already seen them.",
      "You definitely own a podcast microphone that you've used exactly once.",
      "Bro's stress is 100% caused by his fantasy football team losing again.",
      "You look like you still wear the same pair of sneakers you bought 4 years ago to 'nice' events.",
      "Your cortisol spiked because you realized you actually have to schedule your own dentist appointments now.",
      "You radiate 'I invest in crypto but don't understand inflation' energy.",
      "Grown man. Your apartment definitely still has unframed posters taped to the wall.",
      "You look like you think grilling a steak properly is the pinnacle of culinary achievement.",
      "Your biggest flex is that you 'used to play college ball' even though it was D3 and you rode the bench.",
      "Bro, your stress comes from pretending to care during corporate Zoom meetings.",
      "You look like you describe yourself as 'fiscally conservative but socially liberal' to avoid taking a real stance.",
      "You definitely still use 3-in-1 body wash because buying separate bottles is 'too much work'.",
      "Your cortisol is high because your back hurts and you literally just slept wrong.",
      "You have the energy of a guy who gives unsolicited gym advice to people with headphones on.",
      "Grown man. You probably think acknowledging your feelings makes you less manly.",
      "You look like you still haven't figured out how to properly fold a fitted sheet. Just balling it up, huh?",
      "Your stress is fueled by the realization that you have to work for the next 40 years.",
      "Bro definitely tries to bargain at chain retail stores.",
      "You look like you think 'I'm a nice guy' is an adequate dating profile bio.",
      "Your cortisol spiked because a younger coworker explained a meme that you didn't understand.",
      "You radiate 'I drink IPAs because I think it makes me look sophisticated' energy. It tastes like pine needles.",
      "Adult male. Your entire wardrobe is just different colored polo shirts from the exact same brand.",
      "You look like you still haven't learned that washing your face with bar soap is a crime.",
      "Your biggest fear is someone asking you to name a book you've read in the last year that wasn't an audiobook.",
      "Bro, your stress comes from realizing your metabolism isn't what it used to be and the beer belly is forming.",
      "You definitely refer to your group of friends as 'the boys' even though you're all pushing 30.",
      "You look like you think knowing random WW2 facts constitutes a personality.",
      "Your cortisol is high because you just saw how much a decent mattress actually costs.",
      "Grown man. You probably still use the same password for every single account you own.",
      "You look like you describe basic human decency as 'simping'.",
      "Your stress is 100% caused by the check engine light that's been on for three months.",
      "Bro definitely thinks 'playing devil's advocate' makes him intellectually superior.",
      "You look like you still haven't accepted that your sports team is in a 'rebuilding decade'.",
      "Your cortisol spiked because you accidentally hit 'reply all' on a company-wide email.",
      "You radiate 'I need to stretch before I sneeze so I don't pull a muscle' energy.",
      "Adult male. Your definition of home decor is a single plant that's currently dying.",
      "You look like you still think buying a woman a drink guarantees a conversation.",
      "Your biggest achievement this year was successfully assembling IKEA furniture without leftover pieces.",
      "Bro, your stress comes from realizing you actually have to buy Christmas presents for your family now.",
      "You definitely brag about functioning on 4 hours of sleep like it's an Olympic sport.",
      "You look like you still hold onto the belief that you could step in for the injured quarterback and win the game.",
      "Your cortisol is high because you just realized your favorite song is now playing on the 'classic rock' station.",
      "Grown man. You probably still haven't figured out how to use the 'delicates' cycle on your washing machine.",
      "You look like you think a firm handshake covers up a weak character.",
      "Your stress is fueled by pretending to understand the nuance of the wine you just ordered.",
      "Bro definitely thinks watching 'The Wolf of Wall Street' multiple times gave him business acumen.",
      "You look like you still haven't accepted that cargo shorts are out of style. Let them go.",
      "Your cortisol spiked because you saw a teenager with a better car than yours.",
      "You radiate 'I aggressively merge in traffic to save 3 seconds on my commute' energy.",
      "Adult male. Your idea of taking care of yourself is finally replacing your toothbrush after 8 months.",
      "You look like you still write 'see attached' in emails without actually attaching the file.",
      "Your biggest fear is realizing your dad jokes aren't ironic anymore; they're just who you are.",
      "Bro, your stress comes from trying to remember the name of an acquaintance you've greeted warmly 5 times.",
      "You definitely act like fixing a leaky faucet makes you Bob the Builder, even though you just used duct tape.",
      "You look like you think knowing how to change a tire is a substitute for emotional intelligence.",
      "Your cortisol is high because you just realized you're the 'old guy' at the party.",
      "Grown man. You probably still use 'lmao' in professional Slack channels.",
      "You look like you describe your aggressive driving as 'efficient'.",
      "Your stress is 100% caused by trying to assemble a piece of furniture while refusing to look at the instructions.",
      "Bro definitely thinks bringing up his credit score on a first date is a power move.",
      "You look like you still haven't learned how to properly apologize without adding a 'but...' at the end.",
      "Your cortisol spiked because you just felt a slight twinge in your knee sitting down.",
      "You radiate 'I listen to business podcasts at 1.5x speed while doing the dishes' energy.",
      "Adult male. Your entire skincare routine is splashing water on your face in the shower.",
      "You look like you still think owning a dog is a viable alternative to developing a personality.",
      "Your biggest achievement today was managing to keep a straight face while your boss told a terrible joke.",
      "Bro, your stress comes from the realization that your hangover now lasts an entire weekend.",
      "You definitely pretend to care about artisanal coffee but secretly prefer the gas station stuff.",
      "You look like you still haven't accepted that you can't digest dairy like you used to.",
      "Your cortisol is high because you just got out of breath tying your shoes.",
      "Grown man. You probably still use the same wallet you got for your 18th birthday, and it's practically disintegrating.",
      "You look like you describe yourself as 'an ideas guy' because you refuse to do any actual execution.",
      "Your stress is fueled by the crushing reality that you'll have to mow the lawn this weekend.",
      "Bro definitely thinks buying expensive golf clubs will magically fix his terrible swing.",
      "You look like you still haven't figured out that commenting '🔥' on random women's posts is embarrassing.",
      "Your cortisol spiked because you just realized you forgot an important anniversary. Again.",
      "You radiate 'I have strong opinions about the correct way to load a dishwasher' energy.",
      "Adult male. Your idea of a sophisticated meal is putting hot sauce on eggs.",
      "You look like you still pretend you enjoy going to noisy clubs when you'd rather be asleep by 10.",
      "Your biggest fear is the barber showing you the back of your head in the mirror.",
      "Bro, your stress comes from trying to decipher if an email from your boss is passive-aggressive or just brief.",
      "You definitely act like knowing how to drive a manual transmission makes you a superior human being.",
      "You look like you still haven't accepted that you need reading glasses. Stop squinting at the menu.",
      "Your cortisol is high because you just checked the price of lumber at Home Depot.",
      "Grown man. You probably still rely on your mom for medical advice instead of going to a doctor.",
      "You look like you describe your stubbornness as 'standing your ground'.",
      "Your stress is 100% caused by the pressure of being the 'grill master' at the family barbecue.",
      "Bro definitely thinks knowing the full names of obscure craft beers makes him interesting.",
      "You look like you still panic internally when a waiter asks how you want your steak cooked, then confidently say 'medium-rare' anyway.",
    ],

    // 100 Adult Female Roasts
    DemographicCategory.adultFemale: [
      "Adult woman detected. Your cortisol is fueled by doing literally everything for everyone else.",
      "You look like you keep saying 'I'm fine' while absolutely nothing is fine.",
      "Queen, your stress levels indicate you carry the entire emotional labor of at least 3 relationships.",
      "Adult female. You radiate 'I have 47 unread emails and a skincare routine that takes 45 minutes' energy.",
      "You look like your Google Calendar has anxiety looking at itself.",
      "Your cortisol spike is because you said 'yes' to plans you definitely did not want to attend.",
      "Woman detected. The algorithm can see that you haven't had a proper vacation since 2019.",
      "You have 'I'll sleep when I'm dead but also I need 8 hours minimum' energy.",
      "Adult female stress. You're one glass of wine away from either a breakdown or a breakthrough.",
      "You look like you apologize when someone else bumps into YOU. Stop that.",
      "Ma'am, your cortisol is high because you just realized you're the only one who knows where anything is in your house.",
      "You definitely buy organizational bins thinking it will fix your chaotic life. It won't.",
      "Your stress comes from drafting a work email for 20 minutes to make sure it doesn't sound 'too aggressive'.",
      "You look like you schedule a 'cry session' into your perfectly color-coded planner.",
      "Queen, your cortisol spiked because you accidentally hit 'reply all' on an email complaining about the meeting.",
      "You radiate 'I need to clean the house before the cleaning lady comes' energy.",
      "Adult woman. Your entire personality relies on having a Stanley cup filled with lukewarm water.",
      "You look like you think buying expensive candles is a valid form of therapy.",
      "Your biggest fear is someone dropping by your house unannounced. Truly terrifying.",
      "Girl, your stress is 100% caused by planning a girls' trip that will inevitably never make it out of the group chat.",
      "You definitely have a drawer full of 'nice' gift bags that you hoard for future use.",
      "You look like you still haven't forgiven yourself for an awkward conversation you had in 2014.",
      "Your cortisol is high because you have to make a phone call to dispute a charge.",
      "You have the vibe of a woman who gives incredible advice to her friends but makes catastrophic life choices herself.",
      "Adult female. You probably think doing a face mask counts as 'getting your life together'.",
      "You look like you still panic when you have to parallel park in front of an outdoor cafe.",
      "Your stress is fueled by the crushing guilt of throwing away a decorative box because 'it's a good box'.",
      "Ma'am definitely thinks watching true crime documentaries before bed is relaxing.",
      "You look like you own an absurd number of tote bags but use the same dirty one every day.",
      "Your cortisol spiked because you just saw someone from high school when you went to the grocery store in sweatpants.",
      "You radiate 'I mentally redecorate every home I walk into' energy.",
      "Adult woman. Your definition of a wild Friday night is starting a new Netflix series and falling asleep by 9:30.",
      "You look like you still haven't accepted that you can't keep a fiddle-leaf fig plant alive.",
      "Your biggest achievement this year was finally unpacking the last box from moving two years ago.",
      "Girl, your stress comes from realizing you have to cook dinner again. Every single day until you die.",
      "You definitely pretend to like hiking for the Instagram aesthetic but secretly hate the bugs and sweating.",
      "You look like you still harbor resentment towards a coworker who took your favorite pen.",
      "Your cortisol is high because you just realized your perfectly planned weekend now has a massive gap of free time and you don't know how to relax.",
      "You have the energy of a woman who texts 'omg so true' while staring blankly at the wall.",
      "Adult female. You probably still use the 'hide my age' feature on dating apps even though nobody cares.",
      "You look like you describe your mild social anxiety as being an 'empath'.",
      "Your stress is 100% caused by holding in your true feelings to avoid inconveniencing anyone.",
      "Ma'am definitely thinks buying a matching athleisure set will magically motivate her to work out.",
      "You look like you still haven't figured out how to gracefully accept a compliment without self-deprecating.",
      "Your cortisol spiked because your boss asked to 'chat quickly' without giving any context.",
      "You radiate 'I bought this dress on sale for an event I haven't been invited to yet' energy.",
      "Adult woman. Your idea of a balanced diet is eating a salad for lunch so you don't feel guilty about an entire sleeve of Oreos later.",
      "You look like you still think deleting an app cancels the subscription.",
      "Your biggest fear is opening the front camera by mistake and seeing your double chin.",
      "Girl, your stress comes from pretending you understand what the mechanic is saying about your car.",
      "You definitely act like organizing your spice rack constitutes a major life milestone.",
      "You look like you still haven't accepted that you look exactly the same in all 40 selfies you just took.",
      "Your cortisol is high because you just checked the price of groceries. Welcome to adulthood.",
      "You have the vibe of a woman who loudly declares she's on a diet right before ordering the most caloric thing on the menu.",
      "Adult female. You probably still hold grudges over minor slights from neighborhood moms.",
      "You look like you think knowing your zodiac chart excuses your inability to arrive on time.",
      "Your stress is fueled by the agonizing process of choosing an outfit when you have a closet full of clothes and 'nothing to wear'.",
      "Ma'am definitely thinks drinking a glass of red wine counts as antioxidants.",
      "You look like you still haven't figured out how to fold a fitted sheet and just shove it in the closet in a ball of shame.",
      "Your cortisol spiked because you accidentally liked a picture of your ex's new partner from three years ago.",
      "You radiate 'I have strong opinions about the best brand of paper towels' energy.",
      "Adult woman. Your entire morning routine is a frantic rush because you hit snooze exactly three times.",
      "You look like you still pretend you don't care about getting older but silently panic at every new fine line.",
      "Your biggest achievement today was not crying when you dropped your keys in the parking lot.",
      "Girl, your stress comes from trying to decipher the unwritten rules of corporate casual attire.",
      "You definitely act like going to Target is a therapeutic experience rather than a financial mistake.",
      "You look like you still haven't accepted that holding your stomach in all day is giving you acid reflux.",
      "Your cortisol is high because you just remembered an embarrassing thing you did when you were 12.",
      "You have the energy of a woman who buys fresh produce with the best intentions and then lets it rot in the crisper drawer.",
      "Adult female. You probably still use a planner but only write in it for the first two weeks of January.",
      "You look like you describe your coffee addiction as a cute quirk rather than a chemical dependency.",
      "Your stress is 100% caused by the mental gymnastics of calculating the 'right' amount to tip when the service is terrible.",
      "Ma'am definitely thinks having a curated aesthetic on Instagram makes up for a messy bedroom.",
      "You look like you still haven't figured out how to say 'no' without offering a rambling, fake excuse.",
      "Your cortisol spiked because you thought you lost your phone while you were literally holding it.",
      "You radiate 'I mentally rehearse conversations before having them and still mess them up' energy.",
      "Adult woman. Your idea of self-care is washing your hair and declaring yourself a new person.",
      "You look like you still pretend you enjoy going to brunch when all you really want is to sleep in.",
      "Your biggest fear is running into an acquaintance and having to engage in small talk.",
      "Girl, your stress comes from the crushing realization that you have to decide what's for dinner until the end of time.",
      "You definitely act like buying a new notebook will suddenly make you an organized person.",
      "You look like you still haven't accepted that dry shampoo is not a substitute for an actual shower.",
      "Your cortisol is high because you just checked the weather forecast and it completely ruins your perfectly planned outfit.",
      "You have the vibe of a woman who uses exclamation points in emails so she doesn't seem like a threat.",
      "Adult female. You probably still harbor a secret rivalry with someone who doesn't even know you exist.",
      "You look like you think posting an inspirational quote on your story makes you deeply profound.",
      "Your stress is fueled by the agonizing task of trying to find the perfect shade of nude lipstick.",
      "Ma'am definitely thinks watching HGTV gives her the qualifications to renovate a kitchen.",
      "You look like you still haven't figured out how to graciously accept a gift you despise.",
      "Your cortisol spiked because you were the first person to arrive at a social gathering. Unbearable.",
      "You radiate 'I have a Pinterest board dedicated to a lifestyle I will never attain' energy.",
      "Adult woman. Your entire evening is ruined if you can't find the perfect TV show to watch while eating your food.",
      "You look like you still pretend you know how to pair wine with food instead of just picking the second cheapest bottle.",
      "Your biggest achievement today was successfully ignoring an unknown number calling your phone.",
      "Girl, your stress comes from the constant internal debate of whether to cut bangs or not.",
      "You definitely act like finishing a tube of lip balm without losing it is a major victory.",
      "You look like you still haven't accepted that high heels are a medieval torture device and pretend they are 'comfortable'.",
      "Your cortisol is high because you just realized you spent an entire hour doomscrolling instead of doing literally anything productive.",
      "You have the energy of a woman who loudly insists she's 'fine' while visibly radiating hostility.",
      "Adult female. You probably still use 'adulting' as a verb.",
    ],

    // 100 Boomer Male Roasts
    DemographicCategory.boomerMale: [
      "Old man detected. The algorithm is genuinely surprised you know how to use a phone.",
      "Sir, your cortisol has been building since the 80s. It's basically fossilized at this point.",
      "Boomer male detected. You're the reason the phrase 'OK boomer' was invented.",
      "You look like you complain about 'kids these days' while being the generation that ruined the economy.",
      "Old king. Your biggest source of stress is probably your WiFi password that you wrote on a napkin.",
      "You radiate 'I peaked during the dot-com bubble and never recovered' energy.",
      "Sir, you have the face of a man who has yelled at a cloud at least once this week.",
      "Boomer male. Your cortisol is high because you just discovered what your kids post on Instagram.",
      "You look like you still call IT support to ask how to open a PDF.",
      "Old man stress. You're one bad back day away from buying a La-Z-Boy and never getting up again.",
      "Sir, you look like your defining personality trait is a strong opinion on the thermostat setting.",
      "Your cortisol is high because you saw someone with green hair at the grocery store.",
      "You definitely start your texts with 'Dear [Name]' like you're writing a formal letter.",
      "Boomer male. You probably still hold out hope that cargo pants are coming back into style. They aren't.",
      "You look like you think asking 'how much did you pay for that?' is appropriate small talk.",
      "Your stress is 100% caused by the realization that you have a million photos on your phone and don't know how to back them up.",
      "Sir, you radiate 'I still use a Yahoo email address and refuse to change it' energy.",
      "You probably still have a drawer full of AOL free trial CDs 'just in case'.",
      "You look like you give unprompted advice to retail workers who just want you to leave.",
      "Your cortisol spiked because the self-checkout machine asked you to place the item in the bagging area.",
      "Boomer male. You definitely think adding 'the' before an app name makes you sound cooler. 'The Facebook'.",
      "You look like you still believe a firm handshake is the only requirement for getting a job today.",
      "Your biggest fear is losing the little piece of paper where you wrote down all your passwords.",
      "Sir, your stress comes from trying to figure out which remote turns on the TV.",
      "You definitely act like driving without a GPS makes you Christopher Columbus.",
      "You look like you complain about 'participation trophies' but have an entire garage full of useless bowling league plaques.",
      "Your cortisol is high because you just received a scam email and spent an hour trying to reply to it.",
      "You have the energy of a man who stands in the middle of the aisle with his cart completely blocking traffic.",
      "Boomer male. You probably still think buying a house on minimum wage is possible with 'a little elbow grease'.",
      "You look like you describe your inability to use technology as someone else's fault.",
      "Your stress is fueled by the crushing reality that nobody wants to hear your war stories about corporate life in the 90s.",
      "Sir definitely thinks wearing white New Balance sneakers with dad jeans is peak fashion.",
      "You look like you still haven't figured out how to turn off the flashlight on your phone.",
      "Your cortisol spiked because you saw a young person ordering a complicated coffee drink.",
      "You radiate 'I ask the waiter for the check by doing the air signature motion' energy.",
      "Boomer male. Your idea of fixing a computer problem is hitting it aggressively.",
      "You look like you still pretend you know how to fix a car engine despite cars being computers now.",
      "Your biggest achievement this year was figuring out how to set an alarm on your smartwatch.",
      "Sir, your stress comes from realizing you have to update the software on your devices.",
      "You definitely act like you're a connoisseur of classic rock but only listen to the greatest hits albums.",
      "You look like you still haven't accepted that nobody answers unknown numbers anymore.",
      "Your cortisol is high because you just saw the price of a movie ticket and compared it to 1985.",
      "You have the vibe of a man who confidently pronounces foreign words completely wrong.",
      "Boomer male. You probably still harbor resentment over a bad call a referee made in a game twenty years ago.",
      "You look like you think tipping 10% is generous because 'they already get paid an hourly wage'.",
      "Your stress is 100% caused by trying to navigate a digital menu via QR code at a restaurant.",
      "Sir definitely thinks his political opinions posted on Facebook are changing the world.",
      "You look like you still haven't figured out how to cancel a recurring subscription and just accept the monthly charge.",
      "Your cortisol spiked because you hit the wrong button on the TV and changed the input.",
      "You radiate 'I leave voicemails that just say call me back' energy.",
      "Boomer male. Your entire morning routine is complaining about the news while reading a physical newspaper.",
      "You look like you still pretend you don't need hearing aids while asking everyone to repeat themselves.",
      "Your biggest fear is someone checking your browser history and finding your embarrassing searches for 'how to use the google'.",
      "Sir, your stress comes from the agonizing process of remembering your Apple ID password to download an app.",
      "You definitely act like having a landline gives you some sort of moral superiority.",
      "You look like you still haven't accepted that your opinion isn't required in every single situation.",
      "Your cortisol is high because you just discovered your favorite brand of shaving cream was discontinued.",
      "You have the energy of a man who meticulously maintains his lawn but neglects his emotional relationships.",
      "Boomer male. You probably still use a physical map and proudly boast about your navigation 'instincts'.",
      "You look like you describe your blatant rudeness as just 'telling it like it is'.",
      "Your stress is fueled by the fact that you can't figure out how to un-mute yourself on a Zoom call.",
      "Sir definitely thinks loudly repeating 'I can't hear you' is faster than turning up the volume.",
      "You look like you still haven't figured out that typing in all caps is considered yelling in the digital world.",
      "Your cortisol spiked because you accidentally switched the camera to front-facing while trying to take a picture of a bird.",
      "You radiate 'I demand to speak to a human representative' energy.",
      "Boomer male. Your idea of a sophisticated meal is steak and potatoes, and anything else is 'rabbit food'.",
      "You look like you still pretend you understand the complexities of modern dating when you met your partner at a barn dance in 1978.",
      "Your biggest achievement today was accurately forwarding an email joke to your entire contact list.",
      "Sir, your stress comes from realizing you have to remember a new pass-code for the alarm system.",
      "You definitely act like having calluses on your hands makes you a better person.",
      "You look like you still haven't accepted that people work from home and assume they are just lazy.",
      "Your cortisol is high because you just saw an article about a new slang word and you are inexplicably angry about it.",
      "You have the vibe of a man who takes the phrase 'back in my day' as a personal challenge in every conversation.",
      "Boomer male. You probably still hold on to VHS tapes of movies you haven't watched in three decades.",
      "You look like you think your outdated pop culture references from the 70s are universally understood.",
      "Your stress is 100% caused by the flashing 12:00 on the VCR that you still refuse to throw away.",
      "Sir definitely thinks his unsolicited career advice to a barista is life-changing.",
      "You look like you still haven't figured out how to use Bluetooth headphones and proudly stick to wires.",
      "Your cortisol spiked because you couldn't figure out how to turn off the caps lock on your keyboard.",
      "You radiate 'I have a favorite chair and if anyone else sits in it, the day is ruined' energy.",
      "Boomer male. Your entire wardrobe is slowly transitioning into entirely khaki and fleece.",
      "You look like you still pretend you're a 'handyman' but end up calling a professional after breaking it worse.",
      "Your biggest fear is realizing your kids are right about something and having to admit it.",
      "Sir, your stress comes from the sheer terror of having to remember which streaming service has the show you want to watch.",
      "You definitely act like ordering something on Amazon makes you a tech genius.",
      "You look like you still haven't accepted that you can't pause an online multiplayer game.",
      "Your cortisol is high because you just saw the neighbor put their trash cans out incorrectly.",
      "You have the energy of a man who meticulously checks his tire pressure but ignores his high blood pressure.",
      "Boomer male. You probably still believe that leaving appliances plugged in drains the electricity.",
      "You look like you describe your refusal to learn new things as 'sticking to tradition'.",
      "Your stress is fueled by the excruciating process of trying to set up a new router.",
      "Sir definitely thinks loudly complaining about customer service wait times will make the music stop faster.",
      "You look like you still haven't figured out how to attach a file to an email without calling for help.",
      "Your cortisol spiked because you accidentally minimized a window on your computer and think you deleted the internet.",
      "You radiate 'I proudly clip coupons out of the newspaper and hold up the line at the grocery store' energy.",
      "Boomer male. Your idea of a wild weekend is waking up early to get ahead on yard work.",
      "You look like you still pretend you're going to fix that broken lawnmower sitting in the garage since 2012.",
      "Your biggest achievement today was successfully ignoring a telemarketer.",
      "Sir, your stress comes from the agonizing task of trying to decipher a text message containing only emojis.",
      "You definitely act like complaining about the younger generation is a full-time job with benefits.",
    ],

    // 100 Boomer Female Roasts
    DemographicCategory.boomerFemale: [
      "Ma'am detected. The AI is honored that someone from your generation found this app.",
      "Elder queen. Your cortisol has been accumulating since before the internet existed.",
      "Boomer female detected. You radiate 'let me speak to the manager' energy even when you're relaxed.",
      "You look like you share motivational quotes on Facebook at 6 AM. Every. Single. Day.",
      "Your cortisol spike is probably from learning that your grandkids say 'rizz' unironically.",
      "Ma'am, your stress levels indicate you've raised at least one child who still doesn't call enough.",
      "You have the face of a woman who has perfected the art of the disapproving sigh.",
      "Boomer female. Your biggest stressor is that nobody appreciates your casserole recipe anymore.",
      "You look like you've been to every Homegoods in a 50-mile radius and have opinions about all of them.",
      "Old queen stress. You're one holiday season away from snapping at the entire family dinner table.",
      "Ma'am, your cortisol is high because you just saw a typo on a restaurant menu.",
      "You definitely leave long, rambling voicemails when a text would have sufficed.",
      "Your stress comes from the intense pressure of being the neighborhood watch captain even though you weren't elected.",
      "You look like you use iPads with an aggressive, one-finger poking technique.",
      "Elder queen, your cortisol spiked because someone failed to return a Tupperware container.",
      "You radiate 'I keep decorative soaps in the bathroom that no one is allowed to use' energy.",
      "Boomer female. Your entire home decor aesthetic is 'Live, Laugh, Love' signs in varying fonts.",
      "You look like you think posting 'amen' on a Facebook photo cures diseases.",
      "Your biggest fear is throwing a party and running out of finger sandwiches.",
      "Ma'am, your stress is 100% caused by trying to figure out how to switch your TV to HDMI 2.",
      "You definitely sign your text messages with your name. We know who it's from, Brenda.",
      "You look like you still harbor resentment over a slight from a PTA meeting in 1998.",
      "Your cortisol is high because you just saw a teenager wearing ripped jeans and it deeply offended you.",
      "You have the vibe of a woman who uses quote fingers aggressively in conversation.",
      "Boomer female. You probably still think putting your credit card info online is akin to giving it to a pirate.",
      "You look like you describe your passive-aggressive behavior as 'just being helpful'.",
      "Your stress is fueled by the crushing reality that your children don't want your heirloom china.",
      "Ma'am definitely thinks knowing the names of the cashiers at the grocery store makes her a local celebrity.",
      "You look like you still haven't figured out how to turn off the keyboard click sound on your phone.",
      "Your cortisol spiked because you accidentally switched your phone to a foreign language and don't know how to change it back.",
      "You radiate 'I have strong opinions about the correct way to load a dishwasher and will redo yours behind your back' energy.",
      "Boomer female. Your idea of a balanced diet is taking 14 different vitamins every morning.",
      "You look like you still pretend you enjoy hosting family holidays when it secretly gives you migraines.",
      "Your biggest achievement this year was figuring out how to do a video call without pointing the camera straight up your nose.",
      "Ma'am, your stress comes from realizing you have to memorize a new PIN code.",
      "You definitely act like having a well-kept garden is a moral imperative.",
      "You look like you still haven't accepted that nobody wants to read a five-page holiday newsletter.",
      "Your cortisol is high because you just saw the neighbor's grass is slightly taller than regulation.",
      "You have the energy of a woman who loudly shushes people in a movie theater during the previews.",
      "Boomer female. You probably still use the same password for every account and keep it written on a sticky note under your keyboard.",
      "You look like you think complaining to a teenager working at a retail store will change corporate policy.",
      "Your stress is 100% caused by the mental gymnastics of planning seating arrangements for a dinner party.",
      "Ma'am definitely thinks watching daytime soap operas is a valid cultural experience.",
      "You look like you still haven't figured out how to use the self-checkout and loudly complain about it to anyone who will listen.",
      "Your cortisol spiked because you received an invitation via email instead of on heavy cardstock.",
      "You radiate 'I buy gifts for people months in advance and then forget where I hid them' energy.",
      "Boomer female. Your entire wardrobe transitioned to elastic waistbands without you realizing it.",
      "You look like you still pretend you don't need reading glasses while holding the menu at arm's length.",
      "Your biggest fear is someone checking your browser history and finding your embarrassing searches for 'how to make a meme'.",
      "Ma'am, your stress comes from the agonizing process of trying to remember the name of an actor from a movie you saw 20 years ago.",
      "You definitely act like clipping coupons is a high-stakes competitive sport.",
      "You look like you still haven't accepted that your grandchildren don't want to play Monopoly.",
      "Your cortisol is high because you just discovered a speck of dust on your pristine coffee table.",
      "You have the vibe of a woman who meticulously maintains a 'guest room' that is used exactly once a year.",
      "Boomer female. You probably still use the phrase 'roll down the window'.",
      "You look like you describe your gossiping as 'showing concern'.",
      "Your stress is fueled by the excruciating process of trying to set up a new smart speaker.",
      "Ma'am definitely thinks loudly saying 'hello?' repeatedly on a bad connection fixes the signal.",
      "You look like you still haven't figured out that hitting reply-all on a chain email annoys everyone.",
      "Your cortisol spiked because you accidentally 'liked' a comment from someone you claim to despise.",
      "You radiate 'I proudly bring store-bought cookies to a bake sale and pretend I made them' energy.",
      "Boomer female. Your idea of a wild weekend is rearranging the furniture in the living room.",
      "You look like you still pretend you're going to finish that knitting project you started in 2018.",
      "Your biggest achievement today was successfully unsubscribing from a catalog you've received for a decade.",
      "Ma'am, your stress comes from the agonizing task of trying to decipher a recipe online amidst ads and background stories.",
      "You definitely act like having a perfectly curated collection of throw pillows makes you superior.",
      "You look like you still haven't accepted that people don't use the 'good room' for everyday activities.",
      "Your cortisol is high because you just saw an article about a new fashion trend and you are inexplicably angry about it.",
      "You have the energy of a woman who takes the phrase 'back in my day' as a personal challenge in every conversation.",
      "Boomer female. You probably still hold on to issues of Reader's Digest from the 90s.",
      "You look like you think your outdated parenting advice is universally applicable.",
      "Your stress is 100% caused by the flashing 12:00 on the microwave that you still refuse to learn how to fix.",
      "Ma'am definitely thinks her unsolicited critiques on a local business's Facebook page are changing the world.",
      "You look like you still haven't figured out how to use GPS and rely on printed MapQuest directions.",
      "Your cortisol spiked because you couldn't figure out how to turn down the brightness on your tablet.",
      "You radiate 'I cover all the furniture in plastic to keep it nice for company' energy.",
      "Boomer female. Your entire morning routine involves complaining about the news while drinking weak coffee.",
      "You look like you still pretend you understand the complexities of modern dating when you met your partner at a drive-in theater in 1974.",
      "Your biggest fear is realizing your daughter-in-law makes a better pie than you.",
      "Ma'am, your stress comes from the sheer terror of having to remember which streaming service has the show you tolerate watching.",
      "You definitely act like ordering something from QVC makes you a savvy shopper.",
      "You look like you still haven't accepted that you can't just 'drop in' unannounced anymore.",
      "Your cortisol is high because you just saw the neighbor painted their front door a color not approved by the HOA.",
      "You have the vibe of a woman who meticulously checks expiration dates but ignores her own diminishing patience.",
      "Boomer female. You probably still believe that sugar makes kids hyperactive despite scientific evidence.",
      "You look like you describe your refusal to learn new things as 'sticking to tradition'.",
      "Your stress is fueled by the excruciating process of trying to return a wrong item bought online.",
      "Ma'am definitely thinks loudly complaining about customer service wait times will make the music stop faster.",
      "You look like you still haven't figured out how to attach a photo to a text message without creating a new thread.",
      "Your cortisol spiked because you accidentally minimized a window on your computer and think you deleted the family photos.",
      "You radiate 'I proudly clip articles out of the newspaper and mail them to my adult children' energy.",
      "Boomer female. Your idea of a sophisticated meal is anything that involves Jell-O as a main ingredient.",
      "You look like you still pretend you're going to organize the basement full of boxes from the 80s.",
      "Your biggest achievement today was successfully ignoring a telemarketer by pretending you don't speak English.",
      "Ma'am, your stress comes from the agonizing task of trying to decipher a meme your grandchild sent you.",
      "You definitely act like complaining about the younger generation is a full-time job with benefits.",
      "You look like you still haven't accepted that 'text speak' is a real thing and judge people for typing 'lol'.",
      "Your cortisol is high because you just saw someone wearing white after Labor Day. The horror.",
      "You radiate 'I keep a bowl of hard candies in my purse that have fused together' energy.",
      "Boomer female. You probably still have a decorative spoon collection displayed prominently.",
      "You look like you describe minor inconveniences as 'a real trial'.",
    ],
  };
}
